root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server && ./tmp/server"
  bin = "./tmp/server"
  include_ext = ["go", "sql"]
  exclude_dir = ["tmp", "frontend", "node_modules", "data"]
  delay = 1000

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
