package auth_test

import (
	"strings"
	"testing"
	"time"

	"github.com/solomon/finance-visualizer/internal/auth"
	"golang.org/x/crypto/bcrypt"
)

func TestVerifyPassword_Correct(t *testing.T) {
	hash, err := bcrypt.GenerateFromPassword([]byte("testpass"), bcrypt.DefaultCost)
	if err != nil {
		t.Fatalf("failed to generate bcrypt hash: %v", err)
	}
	if err := auth.VerifyPassword(string(hash), "testpass"); err != nil {
		t.Errorf("VerifyPassword returned error for correct password: %v", err)
	}
}

func TestVerifyPassword_Wrong(t *testing.T) {
	hash, err := bcrypt.GenerateFromPassword([]byte("testpass"), bcrypt.DefaultCost)
	if err != nil {
		t.Fatalf("failed to generate bcrypt hash: %v", err)
	}
	if err := auth.VerifyPassword(string(hash), "wrongpass"); err == nil {
		t.Error("VerifyPassword returned nil error for wrong password; expected error")
	}
}

func TestVerifyPassword_EmptyHash(t *testing.T) {
	if err := auth.VerifyPassword("", "anypassword"); err == nil {
		t.Error("VerifyPassword returned nil error for empty hash; expected error")
	}
}

func TestCreateToken_ReturnsValidJWT(t *testing.T) {
	auth.Init("test-secret-key-for-jwt-signing")
	tokenStr, err := auth.CreateToken()
	if err != nil {
		t.Fatalf("CreateToken returned error: %v", err)
	}
	if tokenStr == "" {
		t.Error("CreateToken returned empty token string")
	}
	// A valid JWT has 3 dot-separated parts
	parts := strings.Split(tokenStr, ".")
	if len(parts) != 3 {
		t.Errorf("expected 3 JWT parts, got %d: %q", len(parts), tokenStr)
	}
}

func TestCreateToken_Has30DayExpiry(t *testing.T) {
	auth.Init("test-secret-key-for-jwt-signing")
	tokenStr, err := auth.CreateToken()
	if err != nil {
		t.Fatalf("CreateToken returned error: %v", err)
	}

	ta := auth.TokenAuth()
	if ta == nil {
		t.Fatal("TokenAuth() returned nil after Init")
	}

	token, err := ta.Decode(tokenStr)
	if err != nil {
		t.Fatalf("failed to decode token: %v", err)
	}

	expTime, ok := token.Expiration()
	if !ok {
		t.Fatal("token has no 'exp' claim")
	}

	expected := time.Now().Add(30 * 24 * time.Hour)
	diff := expTime.Sub(expected)
	if diff < -2*time.Minute || diff > 2*time.Minute {
		t.Errorf("exp claim is %v, expected ~%v (diff: %v)", expTime, expected, diff)
	}
}

func TestInit_SetsTokenAuth(t *testing.T) {
	auth.Init("another-test-secret")
	if auth.TokenAuth() == nil {
		t.Error("TokenAuth() returned nil after calling Init; expected non-nil")
	}
}

func TestHashPassword_ReturnsValidHash(t *testing.T) {
	hash, err := auth.HashPassword("mypassword")
	if err != nil {
		t.Fatalf("HashPassword returned error: %v", err)
	}
	if hash == "" {
		t.Error("HashPassword returned empty string")
	}
	// Verify the generated hash works with VerifyPassword
	if err := auth.VerifyPassword(hash, "mypassword"); err != nil {
		t.Errorf("VerifyPassword failed with hash generated by HashPassword: %v", err)
	}
}
